name: lamna
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_mockup.png
    - assets/logos/logo.svg
    - assets/logos/logoSimple.svg
    - assets/pictures/Location search_pana.png
    - assets/pictures/Madrid_pana.png
    - assets/pictures/Retail markdown_pana.png
    - assets/pictures/World Bicycle Day_pana.png
  fonts:
    - family: ClashDisplay
      fonts: 
        - asset: fonts/ClashDisplay-Variable.ttf
