name: lamna
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_mockup.png
    - assets/logos/logo.svg
    - assets/logos/logoSimple.svg
    - assets/logos/logo_google.png
    - assets/logos/logo_mac_os.png
    - assets/pictures/Location search_pana.png
    - assets/pictures/Madrid_pana.png
    - assets/pictures/Retail markdown_pana.png
    - assets/pictures/World Bicycle Day_pana.png
    - assets/pictures/rennes.png
    - assets/pictures/Rennes/rennes1.png
    - assets/pictures/Rennes/rennes2.png
    - assets/pictures/Rennes/rennes3.png
    - assets/pictures/saint_malo.png
    - assets/pictures/brest.png
    - assets/pictures/lorient.png
    - assets/json/cities.json
  fonts:
    - family: ClashDisplay
      fonts: 
        - asset: fonts/ClashDisplay-Variable.ttf
